global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:7860
    scrape_interval: 10s

  - job_name: mongodb-exporter
    static_configs:
      - targets:
          - mongodb-exporter:9216

  - job_name: redis-exporter
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
          - minio:9000

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: traefik
    static_configs:
      - targets:
          - traefik:8080
