apiVersion: v1
kind: Namespace
metadata:
  name: codespace-op
  labels:
    app.kubernetes.io/name: codespace-op
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
